/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package structurizr.java.example;

import com.structurizr.Workspace;
import com.structurizr.model.Model;
import com.structurizr.model.Person;
import com.structurizr.model.SoftwareSystem;
import com.structurizr.view.SystemContextView;
import com.structurizr.view.ViewSet;

public class App {

    public static void main(String[] args) throws Exception {
        // Create a workspace
        Workspace workspace = new Workspace("My software system", "This is a description of my software system.");
        Model model = workspace.getModel();

        SoftwareSystem mySoftwareSystem = model.addSoftwareSystem("My Software System", "Description");
        Person user = model.addPerson("User", "A user of my software system");
        user.uses(mySoftwareSystem, "Uses");

        ViewSet views = workspace.getViews();
        SystemContextView contextView = views.createSystemContextView(mySoftwareSystem, "Context", "An example of a System Context diagram.");
        contextView.addAllSoftwareSystems();
        contextView.addAllPeople();

        // Export the entire workspace as PlantUML files
        new StructurizrPlantUmlFileExporter().exportToFile(workspace, ".");
    }


}
